analyzed some non-functional aspects
BME-MIT-IET/iet-hf2021-nazsa-2 pull request #14
Opened 2021-05-05 16:02 UTC by jolomarci

2021-05-05 16:03 UTC, vassbence approved these changes
LGTM

2021-05-05 16:06 UTC, vassbence requested changes
Nice work, mentioned some typos

2021-05-05 16:06 UTC, vassbence commented on doc/non-functional-tests-doc.md
> +The application prohibits zooming on the pages, wich could be problematic for users with low vision. Even though the website was made for university students, we should make it accessible for everyon
which

2021-05-05 16:06 UTC, vassbence commented on doc/non-functional-tests-doc.md
> +Another point, where we could improve the application is the choice of colours. Witc better contrast ratio, the site would be better to look at for longer periods of time.
With

2021-05-05 16:19 UTC, Cuslika requested changes

2021-05-05 16:19 UTC, Cuslika commented on doc/non-functional-tests-doc.md
> +The page produced desirable results, the only field where the we should consider some changes was the Accessiblity.
-the

2021-05-05 16:19 UTC, Cuslika commented on doc/non-functional-tests-doc.md
> +Here the results were also promosing with the exception of Security. The used Javascript libraries were safe, however there were some missing HTTP security headers. The page listed some examples, to
promosing typo

2021-05-05 16:21 UTC, Cuslika approved these changes
Okay

2021-05-06 11:03 UTC, vassbence approved these changes
LGTM

2021-05-06 11:03 UTC, merged